# http://module-build.sourceforge.net/META-spec.html
name:         Mobile-P2kMoto
version:      0.03
version_from: lib/Mobile/P2kMoto.pm
installdirs:  site
author:       Mattia Barbon <mbarbon@cpan.org>
abstract:     interface with Motorola P2K phones
license:      gpl
requires:
  XSLoader: 0.01
#build_requires:
no_index:
  directory:
    - inc
    - t
    - example

# extras.
dynamic_config: 0

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.09, EUMM-6.44.
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
